#! /usr/bin/perl

use strict;
use warnings;

use AppConfig qw(:argcount);

use RT::Client::REST;
use RT::Client::REST::Queue;
use RT::Client::REST::Ticket;

unless (@ARGV >= 1) {
	die "$0: need configuration file.\n";
}

my ($cfgfile, $config, $rt, $queue, $ticket, $rootid, $id, $sth);

# Read configuration file
$cfgfile = shift;
$config = read_config($cfgfile, {});

# RT
$rt = new RT::Client::REST (server => $config->{url});
$rt->login(username => $config->{username}, password => $config->{password});

# Do sth
$sth = shift;

if ($sth) {
	# display ticket
	$id = $sth;

	$ticket = new RT::Client::REST::Ticket(rt => $rt, id => $id);

	if ($ticket->retrieve) {
		my @custom_fields = $ticket->cf;
		print "CF: @custom_fields\n";
	}
	print "Due: " . $ticket->due() . "\n";
	print "Tags: " . $ticket->cf('Tags') . "\n";
#	$ticket->cf('Tags', 'Random Tags');
#	$ticket->store;
}

sub read_config {
	my ($file, $confref) = @_;
	my $ac;
	$ac = new AppConfig({GLOBAL => {ARGCOUNT => ARGCOUNT_ONE}});

	for my $var (qw{url queue username password}) {
		$ac->define($var, {DEFAULT => $confref->{$var}});
	}

	$ac->file($file);
	%$confref = $ac->varlist('.*');

	return $confref;
}
