#! /usr/bin/perl

use strict;
use warnings;

use IO::Socket::SSL;
use Mail::IMAPClient;
use PWSConfig;

my ($cref, $imap);

$cref = PWSConfig::setup_vars (required => 'server,user,password,searchtype');

my $conn = new IO::Socket::SSL("$cref->{server}:imaps");

unless ($conn) {
	die "$0: imaps connection to $cref->{server} failed: $!\n";
}
							
$imap = new Mail::IMAPClient (Socket => $conn,
							  User => $cref->{user},
							  Password => $cref->{password});

# set state manually to "Connected"
$imap->{State} = 1;
$imap->login();

unless ($imap->login()) {
	die "Error: " . $imap->LastError() . "\n";
}

# defaults
$cref->{folder} ||= 'INBOX';
$cref->{searchtype} ||= 'ALL';

# select IMAP folder
unless ($imap->select($cref->{folder})) {
	die "$0: Failed to select IMAP folder $cref->{folder}: " . $imap->LastError();
}

# search messages
my @msgs = $imap->search('HEADER', $cref->{searchtype},
						 $imap->Quote($cref->{searchtoken}));
if ($@) {
	die "$0: IMAP search failed: " . $imap->LastError();
}

my @results = $imap->Results();
print "Results for Search: " . join("\n", @results) . "\n";

for my $msgno (@msgs) {
	print "#$msgno ", $imap->subject($msgno), "\n";
}
