#! /usr/bin/perl

use strict;
use warnings;

use IO::Socket::SSL 0.90;
use Mail::IMAPClient;
use PWSConfig;

my ($cref, $imap);

$cref = PWSConfig::setup_vars (required => 'server,user,password');

my $conn = new IO::Socket::SSL("$cref->{server}:imaps");

unless ($conn) {
	die "$0: imaps connection to $cref->{server} failed: $!\n";
}
							
$imap = new Mail::IMAPClient (Socket => $conn,
							  User => $cref->{user},
							  Password => $cref->{password});

# set state manually to "Connected"
$imap->{State} = 1;
$imap->login();

unless ($imap->login()) {
	die "Error: " . $imap->LastError() . "\n";
}

my @folders = $imap->folders();
my $count;

for (sort(@folders)) {
	print "$_ is a folder with ", $imap->message_count($_) || 0, " messages.\n";
}
