#! /usr/bin/perl

use strict;
use warnings;

use Net::SMTP;

use PWSConfig;

my ($cref, $smtp);

$cref = PWSConfig::setup_vars (required => 'server,from,to');

$smtp = new Net::SMTP ($cref->{server},
					   Hello => 'localhost');
unless ($smtp) {
	die "$0: SMTP error: $!\n";
}

$smtp->mail($cref->{from});
$smtp->to($cref->{to});

$smtp->data();
$smtp->datasend(<<EOF);
To: $cref->{to}
Subject: Hello world

Welcome to Net::SMTP.
EOF

$smtp->dataend();

$smtp->quit();
