#! /usr/bin/perl

use Wiki::Toolkit::Setup::DBIxFTSMySQL;

my $dbname = 'wiki';
my $dbuser = 'wiki';
my $dbpass = 'wikisecret';
my $dbhost;

Wiki::Toolkit::Setup::DBIxFTSMySQL::setup($dbname,
								   $dbuser,
								   $dbpass,
								   $dbhost);
