#! /usr/bin/perl

use strict;
use warnings;

use Getopt::Long;
use File::Temp qw(tempfile);
use FindBin;

use Template::Zoom;
use Template::Zoom::Config;
use Template::Zoom::Database::Rose;

my (%opts);

# commandline options
my $whandler = $SIG{__WARN__};
$SIG{__WARN__} = sub {print STDERR "$0: @_";};
unless (GetOptions (\%opts, 'browser')) {
	exit 1;
}
$SIG{__WARN__} = $whandler;

my ($config_file, $config_vars, $db_object, $zoom);

# change directory
chdir($FindBin::RealBin);

# parse configuration file
$config_file = shift;
$config_vars = Template::Zoom::Config::load($config_file);

# database connection
$db_object = new Template::Zoom::Database::Rose(%{$config_vars->{database}});

$zoom = new Template::Zoom(specification_file => 'menu.conf',
						   specification_parser => 'Scoped',
						   template_file => 'menu.html',
						   database => $db_object,
						   filters => {link => \&link_filter},
						  );

if ($opts{browser}) {
	# store zoom result in temporary file
	my ($tmph, $tmpfile) = tempfile('demoXXXX', DIR => '.', SUFFIX => '.html');
	print $tmph $zoom->process({name => 'main'});
	system('x-www-browser', $tmpfile);
}
else {
	print $zoom->process({name => 'main'}), "\n";
}

sub link_filter {
	my $page = shift;
    my $url;

    $url = $page;
	
    return $url;
}
